x = input("Zadej první číslo:")
y = input("Zadej druhé číslo:")
z = input("Zadej třetí číslo:")
a = int(x)
b = int(y)
c = int(z)
print("Součet čísel je:", a + b + c)
print("Součin čísel je:", a * b * c)
